FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
  psycopg2-binary==2.9.9 \
  boto3==1.34.0 \
  xgboost==2.0.3 \
  pandas==2.1.4 \
  numpy==1.26.3 \
  scikit-learn==1.3.2 \
  scipy==1.11.4 \
  pyarrow==15.0.0 && \
  pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu

COPY backend/ /app/
COPY model/ /app/model/

ENV PYTHONPATH=/app

ENTRYPOINT ["python3"]
CMD ["model/wr/train.py"]
